# Basic configuration
provider: "cpu"
num_threads: 4
debug: false

# Model configuration
model:
  # Specify the model type to use: "sense_voice" or "whisper"
  type: "whisper"  

  # SenseVoice model configuration
  sense_voice:
    model_path: "models/model.onnx"
    tokens_path: "models/tokens.txt"
    language: "auto"  # "auto", "zh", "en", "ja", "ko", "yue"
    decoding_method: "greedy_search"
    use_itn: true

  # Whisper model configuration
  whisper:
    encoder_path: "models/whisper/tiny.en-encoder.int8.onnx"
    decoder_path: "models/whisper/tiny.en-decoder.int8.onnx"
    tokens_path: "models/whisper/tiny.en-tokens.txt"
    language: "en"  # "en", "zh", "ja", "ko", etc.
    task: "transcribe"  # "transcribe" or "translate"
    tail_paddings: 0
    decoding_method: "greedy_search"

# VAD configuration
vad:
  model_path: "models/silero_vad.onnx"
  threshold: 0.3 
  min_silence_duration: 0.25
  min_speech_duration: 0.1
  max_speech_duration: 15
  window_size: 256
  sample_rate: 16000