name: Linux Build

on:
  push:
    branches: [ sherpa-onnx ]
  pull_request:
    branches: [ sherpa-onnx ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
    - name: Install git
      run: |
        apt-get update
        apt-get install -y git

    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y cmake build-essential pkg-config ninja-build
        apt-get install -y autoconf libtool libgflags-dev libgtest-dev
        apt-get install -y libc-ares-dev
        apt-get install -y protobuf-compiler libprotobuf-dev
        apt-get install -y libgrpc++-dev libgrpc-dev protobuf-compiler-grpc

    - name: Build sherpa-onnx
      run: |
        cd dep/sherpa-onnx
        mkdir -p build && cd build
        export CC=gcc
        export CXX=g++
        cmake -DCMAKE_INSTALL_PREFIX=./install ..
        make -j$(nproc)
        make install
        cd ../../..

    - name: Configure
      run: |
        export CC=gcc
        export CXX=g++
        mkdir build && cd build
        cmake -G Ninja \
          -DCMAKE_PREFIX_PATH="/usr/lib/x86_64-linux-gnu/cmake" \
          ..

    - name: Build
      run: cd build && ninja 