name: Linux Build

on:
  push:
    branches: [ sherpa-onnx ]
  pull_request:
    branches: [ sherpa-onnx ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y cmake build-essential pkg-config ninja-build
        sudo apt install -y autoconf libtool libgflags-dev libgtest-dev
        sudo apt install -y clang libc++-dev
        sudo apt install -y libc-ares-dev
        sudo apt install -y protobuf-compiler libprotobuf-dev
        sudo apt install -y libgrpc++-dev libgrpc-dev protobuf-compiler-grpc
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          sudo apt-get install -y clang
        fi
        # Debug: List installed gRPC files
        dpkg -L libgrpc++-dev
        dpkg -L libgrpc-dev

    - name: Build sherpa-onnx
      run: |
        cd dep/sherpa-onnx
        mkdir -p build && cd build
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          export CC=clang
          export CXX=clang++
        else
          export CC=gcc
          export CXX=g++
        fi
        cmake -DCMAKE_INSTALL_PREFIX=./install ..
        make -j$(nproc)
        make install
        cd ../../..

    - name: Configure
      run: |
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          export CC=clang
          export CXX=clang++
        else
          export CC=gcc
          export CXX=g++
        fi
        # Try to find gRPC config files
        find /usr -name "*grpc*.cmake" 2>/dev/null || true
        mkdir build && cd build
        cmake -G Ninja \
          ..

    - name: Build
      run: cd build && ninja

    # - name: Package
    #   if: matrix.compiler == 'gcc' && startsWith(github.ref, 'refs/tags/')
    #   run: |
    #     cd build
    #     cpack -G TGZ
    #     mv voice-assistant-*.tar.gz voice-assistant-linux.tar.gz

    # - name: Upload artifact
    #   if: matrix.compiler == 'gcc' && startsWith(github.ref, 'refs/tags/')
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: voice-assistant-linux
    #     path: build/voice-assistant-linux.tar.gz 