name: Release_master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  linux:
    uses: ./.github/workflows/linux.yml
  windows:
    uses: ./.github/workflows/windows.yml

  release:
    needs: [linux, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Display structure of downloaded files
        uses: actions/download-artifact@v4
        with:
          path: artifacts
        run: ls -R artifacts
