name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  linux:
    uses: ./.github/workflows/linux.yml
  windows:
    uses: ./.github/workflows/windows.yml

  release:
    needs: [linux, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: ls artifacts
        run: |
          ls artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/voice-assistant-linux/voice-assistant-*.tar.gz
            artifacts/voice-assistant-windows/voice-assistant-*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
