name: Release_master

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  linux:
    uses: ./.github/workflows/linux.yml
  windows:
    uses: ./.github/workflows/windows.yml

  release:
    needs: [linux, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: ls artifacts
        run: |
          ls artifacts
