name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    uses: ./.github/workflows/linux.yml

  release:
    needs: [linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-artifacts
          path: artifacts/linux

      - name: Create Release Archives
        run: |
          cd artifacts
          tar -czf voice-assistant-linux.tar.gz linux/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/voice-assistant-linux.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true 
