name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  linux:
    uses: ./.github/workflows/linux.yml

  release:
    needs: [linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: voice-assistant-linux-x64
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/voice-assistant-linux-x64.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true 
